<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>SmartLock.UI</AssemblyName>
    <RootNamespace>SmartLock.UI</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SmartLock.Core\SmartLock.Core.csproj" />
  </ItemGroup>
</Project>
